### ISSUE TITLE
KSEM Theme Selection

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#11]

**Comment by LeiYe10** [comment]
This is five alternative themes：
1.https://www.wix.com/website-template/view/html/1329/?siteId=cf13b2ba-9664-430f-ae4c-06e06f269563&metaSiteId=ee8b8eb9-b2a7-4d30-a3e0-105ac27e89b6&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Ftravel-tourism
2.https://www.wix.com/website-template/view/html/1947/?siteId=4641b51a-a8a5-47cc-88e3-a8968c87f8c5&metaSiteId=210176d9-741b-4a13-95d2-34ef2f595e65&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fphotography
3.https://www.wix.com/website-template/view/html/2056/?siteId=1a42c820-1b9f-45c3-9839-4f89a22ace0a&metaSiteId=6262da79-02ae-41f5-b2c0-7cc57613c7d9&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fcommunity-education
4.https://www.wix.com/website-template/view/html/1822/?siteId=70b02fa2-dc4f-4dfa-9ee8-d8008098f0e7&metaSiteId=aceee441-a54e-4dce-83c6-65f38ebdb273&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fcommunity-education
5.https://www.wix.com/website-template/view/html/1723/?siteId=e74a7edb-ff99-4fb9-91e0-1e90bd78d2ee&metaSiteId=9d31fe09-37b5-46a0-a4da-7387bcb58557&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness

**Comment by LeiYe10** [comment]
6. http://demo.cssmoban.com/cssthemes5/twts_98_travelista/index.html
7. http://demo.cssmoban.com/cssthemes5/twts_54_ebusiness/index.html
8. http://demo.cssmoban.com/cssthemes5/fbtp_5_Ambixo/index-gray.html
9. http://demo.cssmoban.com/cssthemes4/cpts_962_bls/index.html
10. http://demo.cssmoban.com/cssthemes4/tplt_1_Freelancer/index.html

**Comment by LeiYe10** [comment]
重点推荐这个  http://demo.cssmoban.com/cssthemes5/twts_97_rango/index.html

**Comment by LeiYe10** [comment]
简洁 大方：
11. https://www.wix.com/website-template/view/html/1659/?siteId=136a7904-0412-4390-b684-705eb1ae9d73&metaSiteId=30036607-67c7-4d57-83f0-3ac12fc6713b&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness%2Fadvertising-marketing
12. https://www.wix.com/website-template/view/html/1407/?siteId=6be387a0-10d3-4c2c-8b6e-929b9c44210b&metaSiteId=44447c61-359d-4140-9a33-7a152318a996&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness%2Fautomotive-cars
13. https://www.wix.com/website-template/view/html/1925/?siteId=907ace81-a1a3-404a-a7ed-6f957a622843&metaSiteId=6b87ee39-1ef4-4a9f-9f8b-f7e87ae941aa&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness%2Ffinance-law
14. https://www.wix.com/website-template/view/html/2079/?siteId=1b082f70-4e00-4a61-9f06-94d35910529a&metaSiteId=e130faca-6118-47e0-bf2b-b51cb00581e8&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness%2Ffinance-law
15. https://www.wix.com/website-template/view/html/2100/?siteId=0d615218-c4d5-4507-9196-7ce96d0f8916&metaSiteId=eb4cd2ac-301f-4759-a7e6-d50b3f5563c5&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness%2Ffinance-law

**Comment by tuliplab** [comment]
I found one template, and please help me to check and compare with the one you need. @LeiYe10 

We will need dropdown menu.

**Comment by tuliplab** [comment]
https://www.dropbox.com/s/p3h5tz70q3lntyl/bizpage-master.zip?dl=0
