### ISSUE TITLE
KSEM Repository Created

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#14]
Current Content: http://www.ksem.info/ksem

Future Deploy URL: www.ksem.conferences.academy

Git Repository
git@bitbucket.org:tulipacademy/www.ksem.conferences.academy.git

@LeiYe10 You need to check out this one which is empty, and start putting template into it. We are using git-flow, mainly via the develop branch.

**Comment by tuliplab** [comment]
@ZiweiHou @LeiYe10 

We aim to get this one done by 10/10/2018. Thanks

**Comment by ZiweiHou** [comment]
@tuliplab @LeiYe10 
I just updated the layouts of index and conference web pages. Please take a look of them, and let me know if there is anything need to be improved. Thanks

**Comment by tuliplab** [comment]
I think: @ZiweiHou 

1. "About Us" can be incorporated into "Home", as a carousel slides.

2. The previous conference CARDS and All, 2016 -, are excellent, good design. Though the ALLL should be on the right hand side.

3. I am not sure how the cards will be connected/incorporated with "Previous Conference" page, and Invited speakers, sponers page. All 3 kinds of information are related to any particular ksem conference.

4. Steering committee section can just be in column "Chairs" "Members", not need to have secretary or web as separate. As both of them are inside members.

As steering comm. page is simple, we can get this one fixed first.


1. the list of KSEM steering committee members.

===

Ruqian Lu (Honorary Chair), Chinese Academy of Sciences, China
Chengqi Zhang (Past Chair), University of Technology, Sydney, Australia
Hui Xiong (Chair), the State University of New Jersey, Rutgers, USA
Dimitris Karagiannis (Deputy Chair), University of Vienna, Austria

===

David Bell, Queen's University, Belfast, UK
Yaxin Bi, Ulster University, Belfast, UK
Cungen Cao, Chinese Academy of Sciences, China
Zhi Jin, Peking University, China
Claudiu Kifor, Sibiu University, Romania
Jérome Lang, University Paul Sabatier, France
Gang Li, Deakin University, Australia
Yoshiteru Nakamori, JAIST, Japan
Jorg Siekmann, German Research Centre of Artificial Intelligence, Germany
Eric Tsui, The Hong Kong Polytechnic University, Hong Kong
Zongtuo Wang, Dalian Science and Technology University, China
Kwok Kee Wei, City University of Hong Kong, Hong Kong
Martin Wirsing, Ludwig-Maximilians-Universität München, Germany
Bo Yang, Jilin University, China
Mingsheng Ying, Tsinghua University, China
Zili Zhang, Southwest University, China (Secretary)

**Comment by tuliplab** [comment]
@ZiweiHou You can create different issues, if regarding different section/page of this site.

For example, any issue/discussion on Steering commeettiie page can be in one issue.

**Comment by ZiweiHou** [comment]
@tuliplab 
Progress update: Merged all pages together

**Comment by ZiweiHou** [comment]
@tuliplab 
Progress update: Update content in Conference and Invited Speaker.
In Progress: layout in Safari and Window Edge, sponsor

**Comment by tuliplab** [comment]
@ZiweiHou 

Please contact @haiyangxia or @LeiYe10 on how to upload the website to server, so that it can be accessed from web browser.
