### ISSUE TITLE
Subdomain for your personal page

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#17]
We will have subdomain name for each infinity member, and you can use it for your personal homepage, or personal blog.

For example, if I want to choose "gangli" as my subdomain name, linked to my home page "http://www.github.io/XXXX", theURLn I will set up one of the following sub domains:

1.  http://gangli.tulip.academy
2.  http://gangli.tulip.org.au

If you want this kind of setup for your site, please leave me message here, with the following information within 2 weeks:

1. Subdomain name:    
2. Preferred domain:   tulip.academy or tulip.org.au
3. Linked URL: xxxx.github.io etc.

If you are using github.io, make sure that the Settings part, GitHub Pages section needs to be properly configured to this customized domain yyy.tulip.academy

**Comment by LeiYe10** [comment]
1.yelei
2.http://yelei.tulip.academy

**Comment by LeiYe10** [comment]
Subdomain name: yelei
Preferred domain: http://yelei.tulip.academy

**Comment by xhan97** [comment]
Subdomain name: xinhan
Preferred domain: http://xinhan.tulip.academy

**Comment by tuliplab** [comment]
linked to where???

@tulip-lab/infinity

**Comment by XiaojuanCheng** [comment]
Subdomain name: XiaojuanCheng
Preferred domain: http://XiaojuanCheng.tulip.academy
link to my blog: https://XiaojuanCheng.github.io

**Comment by lishusmile** [comment]
Subdomain name: shuli
Preferred domain: http://shuli.tulip.academy
link to my blog: https://lishusmile.github.io

**Comment by tuliplab** [comment]
all above done.

some of you didn't configure correctly on your side
