### ISSUE TITLE
IEEE Access Editorial

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#22]
10.1109/ACCESS.2018.2875238

Once the DOI is ready, please add into publication

**Comment by tuliplab** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/4224559/46983187-2d620e80-d12b-11e8-8888-58863ed76197.png">

@xhan97

**Comment by tuliplab** [comment]
This paper appears in: IEEE Access
Issue Date: <not found>
Volume: <not found> Issue: <not found>
On page(s): 1-3
Print ISSN: 2169-3536
Online ISSN: 2169-3536
Digital Object Identifier: 10.1109/ACCESS.2018.2875238

It should be online now @xhan97

**Comment by xhan97** [comment]
Gang Li. IEEE ACCESS special section on curbing crowdturfing in online social networks.
IEEE ACCESS, pages 1–3, 2018.

url: https://doi.org/10.1109/ACCESS.2018.2875238
