### ISSUE TITLE
JTR Paper Accepted

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#25]
JTR-18-06-30.R2 entitled "Cross-Country Analysis of Tourist Activities Based on Venue-Referenced Social Media Data" has completed its review for publication in the Journal of Travel Research.  

Authors: Quan, Gang and Rob

Accepted on 15/11/2018

**Comment by xhan97** [comment]
Web Pages
**Journal**:

Gang Li. Ieee access special section: Curbing crowdturfing in online social networks.
IEEE Access, 6:2169–3536, 2018. 
URL: https://doi.org/10.1109/ACCESS.2018.2875238

Jianming Luo, Huy Quan Vu, Gang Li, and Rob Law. Tourist behavior analysis in gaming
destinations based venue check-in data. Journal of Travel & Tourism Marketing, 2018.

**Processing:**

Qingfeng Chen, Jia Wu, Shichao Zhang, Changan Yuan, Lynn Batten, and Gang Li, editors.
Applications and Techniques in Information Security, volume 69 of Communications
in Computer and Information Science. Springer, November 9-11 2018.
URL: https://doi.org/10.1007/978-981-13-2907-4

**Comment by tuliplab** [comment]
TITLE OF ARTICLE (the "Article"): Cross-Country Analysis of Tourist Activities Based on Venue-Referenced Social Media Data

CORRESPONDING CONTRIBUTOR: Dr. Gang Li 

CONTACT INFORMATION: 221 Burwood Highway Melbourne, Victoria 3125 Australia 

ALL CO-AUTHORS: Vu, Huy Quan; Li, Gang; Law, Rob

@xhan97 @ZiweiHou

**Comment by ZiweiHou** [comment]
Web Pages updated.
