### ISSUE TITLE
CTR Paper Acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#27]
We are delighted to say that we would like to accept your revised manuscript, 'Breach of Traveller Privacy in Location-Based Social Media' (CIT-4577.R2), for publication in  Current Issues in Tourism.  Thank you for your contribution to our journal.

Current Issues in Tourism

**Comment by tuliplab** [comment]
• The DOI of your paper is: 10.1080/13683500.2018.1553151. Once your article has published online, it will be available at the following permanent link: https://doi.org/10.1080/13683500.2018.1553151 .

**Comment by xhan97** [comment]
done
