### ISSUE TITLE
Research Grant Updates

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#28]
Please update this page with: http://www.tulip.org.au/research

Grants part: please format and add ... the following

01/2018-12/2018: X. Liu, F. Chen, G. Li, F. Jiang, “From the cloud to the fog: cost-effective big data placement for mobile social networks”, School of IT Research Funding (AU25K$), Deakin University

Providing Provable Privacy-preserving Data Sharing Services for the Cloud Campus
Prof Wanlei Zhou, Prof Wanlei Zhou, A/Prof Gang Li, Jiage (Jacko) Feng, Dr Tianqing Zhu
ARC Linkage - Projects
2018: $227
INDUSTRY AND OTHER FUNDING

Analyzing the Tourism Carrying Capacity in Macau
A/Prof Gang Li
2015 

Providing Provable Privacy-preserving Data Sharing Services for the Cloud Campus
Prof Wanlei Zhou, Prof Wanlei Zhou, A/Prof Gang Li, Jiage (Jacko) Feng, Dr Tianqing Zhu
2018: $80,000

Building a Secure Cloud-based Collaborative CRM System.
Dr Xiao Liu, A/Prof Gang Li
2018: $25,000
OTHER FUNDING SOURCES

AGD Data Analytics, D2D CRC,
A/Prof Jacob Cybulski, Prof Rens Scheepers, A/Prof Gang Li, Prof Robin Ram Mohan Doss
2017: $13,936

**Comment by ZiweiHou** [comment]
Updated

**Comment by ZiweiHou** [comment]
Updated Conference Chair/PC Chair/Workshop Co-Chairs/Co-Organizers part
