### ISSUE TITLE
Tourism Management Accepted

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#36]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/4224559/59634606-88547580-9192-11e9-991d-59ce9ca57e58.png">

Journal: Tourism Management
Title:  Discovering Implicit Activity Preferences in Travel Itineraries by Topic Modeling
Corresponding Author:  Gang Li
Co-Authors:  Huy Quan Vu, PhD; Rob Law, PhD

**Comment by xhan97** [comment]
DONE
