### ISSUE TITLE
New EIS Paper Acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#37]
Manuscript Title: New Advancement in Information Technologies for Industry 4.0
Manuscript DOI: 10.1080/17517575.2019.1651399
Journal: Enterprise Information Systems

<img width="515" alt="image" src="https://user-images.githubusercontent.com/4224559/62407308-5fc8f380-b5f9-11e9-8643-35c5c59b78e2.png">

**Comment by xhan97** [comment]
Done
