### ISSUE TITLE
IJHTA acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#38]
Ref: Understanding Clusters of Tourist Behavior Associations using Network Analysis

Wei Fan, Rob Law, Gang Li, Davis Fong

Editor in Chief, International Journal of Hospitality & Tourism Administration

**Comment by xhan97** [comment]
Done

**Comment by tuliplab** [comment]
https://doi.org/10.1080/15256480.2019.1692752

DOI , please update

**Comment by xhan97** [comment]
DONE
