### ISSUE TITLE
IJHM 2019

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#39]
Dear All, We congratulate @夏海洋 on the full paper acceptance of IJHM, an A* journal in hospitality. Well done and thanks to the team @Huy Quan Vu  for the great collaboration.

https://www.scimagojr.com/journalsearch.php?q=28686&tip=sid&clean=0

https://www.scimagojr.com/journalrank.php?category=1409

Article title: Evaluation of Hotel Brand Competitiveness Based on Hotel Features Ratings
Journal title: International Journal of Hospitality Management 
author: Mr Haiyang Xia， Huy Quan Vu, Rob Law and Gang Li

**Comment by xhan97** [comment]
Done
