### ISSUE TITLE
One more ™

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#43]
Ms. Ref. No.:  JTMA-D-19-00318R1
Title: Discovering Highly Profitable Travel Patterns by High-Utility Pattern Mining
Tourism Management

Dear Dr. Gang Li,

I am pleased to confirm that your paper "Discovering Highly Profitable Travel Patterns by High-Utility Pattern Mining" has been accepted for publication in Tourism Management.

Comments from the Editor and Reviewers can be found below.

Quan, Gang and Rob

Thank you for submitting your work to this journal.

**Comment by xhan97** [comment]
Done
