### ISSUE TITLE
DOI update

### ISSUE THREAD

**Issue by ZiweiHou** [tulip-lab/tuliplab#45]
@xhan97 Please update DOIs for the following papers,
1.Gang Li, Hao Wang, and Wibowo Hardjawana. New advancement in information technologies for industry 4.0. Enterprise Information Systems, 2019.
2. Zhichao Wang, Qian Li, Gang Li, and Guandong Xu. Polynomial representation for persistence diagram. The IEEE Conference on Computer Vision and Pattern Recognition(CVPR 2019), June 16th - June 20th, 2019, Long Beach, CA. 
Thanks

**Comment by tuliplab** [comment]
Discovering highly profitable travel patterns by high-utility pattern mining
doi: 10.1016/j.tourman.2019.104008
Archive

**Comment by xhan97** [comment]
I can not get the doi of this paper while others have been done.
Gang Li, Hao Wang, and Wibowo Hardjawana. New advancement in information technologies for industry 4.0. Enterprise Information Systems, 2019.

**Comment by xhan97** [comment]
Done

**Comment by tuliplab** [comment]
https://doi.org/10.1080/17517575.2019.1651399

will be here for EIS paper Industry 4.0

**Comment by xhan97** [comment]
Done
