### ISSUE TITLE
JHTR Acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#46]
Journal of Hospitality & Tourism Research

TITLE: Exploration of Tourist Activities in Urban Destination using Venue Check-in Data

CORRESPONDING CONTRIBUTOR: Dr. Gang Li 

ALL CO-AUTHORS: Vu, Huy Quan ; Luo, Jian Ming; Li, Gang; Law, Rob

**Comment by xhan97** [comment]
Done
