### ISSUE TITLE
Expert System Acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#48]
Dear Gang Li, 

Article ID: EXSY12499
Article DOI: 10.1111/exsy.12499  
Article: A homogeneous ensemble method for predicting gastric cancer based on gastroscopy reports
Journal: Expert Systems 

Authors: To be available

**Comment by tuliplab** [comment]
https://onlinelibrary.wiley.com/doi/abs/10.1111/exsy.12504

<img width="717" alt="image" src="https://user-images.githubusercontent.com/4224559/70588450-de294800-1c20-11ea-9091-5adf1b54b02f.png">

@xhan97 author information is ready, please update.

**Comment by xhan97** [comment]
Done
