### ISSUE TITLE
JTTM acceptance: 1st paper in this decade

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#49]
Topic modelling for theme park online reviews: Analysis of Disneyland

Kenny Luo, Quan Vu, Gang Li and Rob Law

Journal of Travel & Tourism Marketing

**Comment by xhan97** [comment]
Done

**Comment by tuliplab** [comment]
DOI is ready, and will be online in 1 week.

Journal Title | Journal of Travel & Tourism Marketing
-- | --
Journal SubTitle |  
Article DOI | 10.1080/10548408.2020.1740138
Article Title | Topic modelling for theme park online reviews: Analysis of Disneyland

**Comment by tuliplab** [comment]
• The DOI of your paper is: 10.1080/10548408.2020.1740138. Once your article has published online, it will be available at the following permanent link: https://doi.org/10.1080/10548408.2020.1740138 .

**Comment by xhan97** [comment]
Done
