### ISSUE TITLE
ECAI2020 Full Paper Acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#50]
TITLE: CIDetector: Semi-Supervised Method for Multi-Topic Confidential Information Detection

AUTHORS: Jianguo Jiang, Yue Lu, Min Yu, Gang Li, Yantao Jia, Jiafeng Guo, Chao Liu and Weiqing Huang

Dear Gang Li,

Congratulations! We are pleased to inform you that the paper

CIDetector: Semi-Supervised Method for Multi-Topic Confidential Information Detection (1239)

has been accepted for presentation at the 24th European Conference on Artificial Intelligence (ECAI 2020).

**Comment by tuliplab** [comment]
This is a CCF B conference, and Australian CORE A conference.

**Comment by xhan97** [comment]
Done
