### ISSUE TITLE
Editorial of IDD Publication

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#52]
Dear Li, Gang; Prabhu, Srikanth; Chen, Qingfeng; Wu, Jia,

“Editorial of Special issue on Information Security and Biometrics”

Accepted by: Information Discovery and Delivery 

The date your article was accepted for publication was: (19-Jan-2020)

**Comment by xhan97** [comment]
Done

**Comment by tuliplab** [comment]
https://doi.org/10.1108/IDD-02-2020-085

DOI available

**Comment by xhan97** [comment]
Done
