### ISSUE TITLE
Data Analytics for Document Security accepted paper list in 2018/2019

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#53]
Please check the following paper list and update if necessary.

![image](https://user-images.githubusercontent.com/4224559/73236458-88b3f500-41e6-11ea-8bc0-50c1971c6c17.png)

**Comment by tuliplab** [comment]
![image](https://user-images.githubusercontent.com/4224559/73244951-359a6c00-41ff-11ea-9da0-d1971ddb4ff7.png)


Please use this one instead

**Comment by xhan97** [comment]
Done
