### ISSUE TITLE
Racism Paper accepted by TM 

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#54]
Tourism Management
Title: Racism in Tourism Reviews
By: Shu Li, Gang Li, Rob Law, Yin Paradise

Article title: Racism in Tourism Reviews
Reference: JTMA_104100
Journal title: Tourism Management
Article Number: 104100
Corresponding author: Dr. Gang Li
First author: Dr. Shu Li
Dear Dr. Li,

Your article Racism in Tourism Reviews will be published in Tourism Management.

To track the status of your article throughout the publication process, please use our article tracking service:

https://authors.elsevier.com/tracking/article/details.do?aid=104100&jid=JTMA&surname=Li

For help with article tracking: http://help.elsevier.com/app/answers/detail/a_id/90

Yours sincerely,
Elsevier Author Support

**Comment by tuliplab** [comment]
Now we have a DOI for this paper:

https://doi.org/10.1016/j.tourman.2020.104100

**Comment by xhan97** [comment]
Done
