### ISSUE TITLE
Two Papers in Journal: Procedia Computer Science

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#55]
Please list both as conference papers, though published in PCS as journal articles.

---------------------------------------------------------------------

Article title: Characterizing the Outlying Feature Set of Groups
Reference: PROCS37534
Journal title: Procedia Computer Science
Corresponding author: Dr. Gang Li
First author: Dr. Haiyang Xia
Final version published online: 27-FEB-2020
Full bibliographic details: Procedia Computer Science  (2019)  pp. 119-125
DOI information: 10.1016/j.procs.2020.01.086

---------------------------------------------------------------------

Article title: Personalized Review Selection
Reference: PROCS37540
Journal title: Procedia Computer Science
Corresponding author: Dr. Gang Li
First author: Dr. Ye Lei
Final version published online: 27-FEB-2020
Full bibliographic details: Procedia Computer Science  (2019)  pp. 158-165
DOI information: 10.1016/j.procs.2020.01.096

http://service.elsevier.com

**Comment by xhan97** [comment]
Done
