### ISSUE TITLE
IJCNN2020: Acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#58]
Congratulations! On behalf of the IJCNN 2020 Technical Program Committee and
Technical Chairs, we are pleased to inform you that your paper:

    Paper ID:   20697
    Author(s):  Wei Luo, Akib Mashrur, Antonio Robles-Kelly and Gang Li
    Title:      Bias-regularised Neural-Network Metamodelling of Insurance Portfolio Risk

has been accepted for presentation at the IJCNN 2020 and for publication in
the conference proceedings published by IEEE. This email provides you with all
the information you require to complete your paper and submit it for inclusion
in the proceedings.

Please read this email carefully. Here are the steps you must follow:

1. Please see the REVIEWERS' COMMENTS for your paper at the end of this email,
which are intended to help you to improve your paper for final publication.
The listed comments should be addressed, as acceptance is conditional on
appropriate response to the requirements and comments.

2. Please prepare your manuscript for final camera ready submission following
the same PDF format guidelines as for the initial submission. Papers are
limited to eight (8) pages in length, must be IEEE Xplore compliant, and must
follow the formatting instructions provided at:

    https://wcci2020.org/submissions/

**Comment by xhan97** [comment]
Done
