### ISSUE TITLE
TULIP Seminar Procedure Polishing Idea

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#6]
结合易师兄的建议，看看哪些可以集成到流程中。

可以在这里讨论时是不是可行、是不是会影响到你们正常研究工作。

只有研究工作是KPI，其他这些事务都是为KPI服务的。

**Comment by tuliplab** [comment]
昨天的组会从组织到会议效果都不错，较之前有了很大的进步。您的介绍非常详细和具体。特别是对课题组的科研方向，您举的几个例子，我是觉得非常有意思，学生也应该对这些方向有了直观的认识，并引起了他们的关注和兴趣。孔老师和王洪涛的PPT也给学生足够鼓励！夏海洋和其它几位同学的现身说法，对什么是科研，如何做科研，如何度过研究生生活，做了很好的示范和解释。特别是夏海洋的PPT，对如何入门科研做了很详细的介绍，我个人也感同身受！所有的学生都进行了发言和自我介绍，参与度高。任萌的组织，包括这次会议的签到，弹幕，很新颖，也贴合现在学生喜欢的交流方式。弹幕这个形式很好，特别是在以后的每周论文讲解中。讲解者可以边讲解，听众可以及时发弹幕。要不听完后，可能有疑问的地方都不记得了。希望技术组看能否找到一种可以直接在PPT共享中分享弹幕的工具或者方法，这样更为直观。

今天的几位做报告的学生，准备都很充分。希望以后每周做论文分享的同学也能做到准备充分——要有自己的理解，自己阅读文献的过程和痕迹，有自己的思考，自己的疑惑，自己解决的方法，而不仅仅是论文的翻译。今天夏海洋的报告最吸引我，因为他讲的很多东西，我都有同感。比如文献的阅读，文献的管理，科研方面的一些方法，因此也听得最投入。我的建议是，现在是大组，对于作报告的同学而言是一个展示的机会，所以事先要在一个小的范围做预演，相当于平时大作业。报告过程中或者结束，参与者要给做PPT的同学打分。每学期可以评出优秀者。对于听的同学，我建议也是要做一篇文献阅读报告，记录自己对文献的理解：比如文献要解决的问题是什么，目前的方法存在什么问题，作者是从那个方面进行突破的，使用的方法是新方法，还是原来的方法改进，实验设计的考虑，没有理解的部分和问题。这样即使每次PPT时，如果提问同学不多，问题也可从这些文档中提取。做PPT的同学以及参与的老师可以共同选出本场最好的参与者，学期末评选最佳参与者。这样可能会让每次的文献分享像这次一样有活力。

昨天晚上新进入组道的学生都很不错，如果能真正管理起来，规范起来，以后个人应该有很大的发展，对研究组也会有很大贡献。希望他们每周都能做一个周计划，包括学习计划，研究计划，上周总结，需要解决的问题，需要研究组或者老师给予的帮助和指导。研究组可以开一个类似BBS论坛的东西（或者直接在我们组的一些社交主页上），可以发一些学生在学习和研究中遇到的问题，可以是匿名的，其它同学和老师可以帮助解答或者解决。暂时想到的就是这么多，希望组会能办得越来越好！李老师，有什么我可以做的，还希望能深度参与。

**Comment by LeiYe10** [comment]
总结一下易峰师兄的建议：1.以后的会议中添加弹幕的形式 2.作报告的同学，事先要在一个小的范围做预演 3.报告过程中或者结束后，参与者要给做PPT的同学打分。每学期可以评出优秀者。4.对于听的同学，要做一篇文献阅读报告，记录自己对文献的理解：（比如文献要解决的问题是什么，目前的方法存在什么问题，作者是从那个方面进行突破的，使用的方法是新方法，还是原来的方法改进，实验设计的考虑，没有理解的部分和问题。）5.希望他们每周都能做一个周计划，包括学习计划，研究计划，上周总结，需要解决的问题，需要研究组或者老师给予的帮助和指导  6.研究组可以开一个类似BBS论坛的东西（或者直接在我们组的一些社交主页上），可以发一些学生在学习和研究中遇到的问题，可以是匿名的，其它同学和老师可以帮助解答或者解决。

**Comment by LeiYe10** [comment]
合理 简单
