### ISSUE TITLE
IEEE ISCC 2020 conference paper acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#60]
----------------------- REVIEW 1 ---------------------
SUBMISSION: 133
TITLE: CES2Vec: A Confidentiality-Oriented Word Embedding for Confidential Information Detection
AUTHORS: Jianguo Jiang, Yue Lu, Min Yu, Gang Li, Chao Liu, Shaohua An and Weiqing Huang

**Comment by xhan97** [comment]
Done
