### ISSUE TITLE
WHMM Acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#61]
Article: Large scale comparative analyses of hotel photo content posted by managers and customers to review platforms based on deep learning: Implications for hospitality marketers

Journal: Journal of Hospitality Marketing & Management  

Authors: Meng Ren, Huy Quan Vu, Gang Li, and Rob Law

The DOI of your paper is: 10.1080/19368623.2020.1765226. Once your article has published online, it will be available at the following permanent link: 

https://doi.org/10.1080/19368623.2020.1765226

**Comment by xhan97** [comment]
Done
