### ISSUE TITLE
DFRWS APAC 2020 proceedings: Conference Paper

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#62]
TITLE: A Novel Adversarial Example Detection Method for Malicious PDFs Using Multiple Mutated Classifiers
AUTHORS: Chao Liu, Chenzhe Lou, Min Yu, S.M. Yiu, K.P. Chow, Gang Li, Jianguo Jiang and Weiqing Huang

Your paper has been accepted for publication in the in the DFRWS APAC 2020 proceedings, which will be published as planned in September 2020.

Please note that the conference in Sydney has been postponed until 17-21 May 2021.

**Comment by xhan97** [comment]
Done
