### ISSUE TITLE
JTR acceptance: Another paper on deep tourism demand forecasting

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#63]
http://dx.doi.org/10.1177/0047287520919522

![image](https://user-images.githubusercontent.com/4224559/82906218-4047f080-9fa8-11ea-95b8-71c7f9fe877e.png)

**Comment by tuliplab** [comment]
Tourism Demand Forecasting: A Decomposed Deep Learning Approach
Yishuo Zhang , Gang Li    , Birgit Muskat    and Rob Law

**Comment by xhan97** [comment]
Done
