### ISSUE TITLE
Conference Acceptance: ACSAC 2020

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#66]
![image](https://user-images.githubusercontent.com/4224559/91009160-52771080-e623-11ea-8ff0-c438b20181e3.png)

**Comment by tuliplab** [comment]
![image](https://user-images.githubusercontent.com/4224559/91009800-ad5d3780-e624-11ea-8a72-38034c5475fc.png)


CCF B Conference

**Comment by tuliplab** [comment]
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/4224559/93844243-e1894e00-fcdf-11ea-9d74-1ba2d178f9a9.png">

**Comment by ZiweiHou** [comment]
Done
