### ISSUE TITLE
JOST: another A* acceptance

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#67]
'Improving resident–tourist relationship in urban hotspot' 

by : Vu, Huy Quan ; Muskat, Birgit; Li, Gang; LAW, Rob.
 Journal of Sustainable Tourism 

• The DOI of your paper is: 10.1080/09669582.2020.1818087. Once your article has published online, it will be available at the following permanent link: https://doi.org/10.1080/09669582.2020.1818087 .

**Comment by ZiweiHou** [comment]
Done
