### ISSUE TITLE
Membership Rights

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/tuliplab#9]
create one table for the requirements and rights of members at different stage.

into slides, and if possible, also poster.

  | Flipper | Trainee | Infinity | Alumni
-- | -- | -- | -- | --
DingTalk | Y | Y | Y | Y
Academy Email | N | Y | Y | Y
Seminar Attendance | Y | Y | Y | N
Seminar Presentation | N | Invitation | Y | Invitation
Seminar Q? | N | Y | Y | Y
Infinity Research Meeting | N | N | Y | N
Reading Team | Y | Y | Invitation | Invitation
High Admin (ID Hiding/Video Call GLi)  | No | No | Y | Y

**Comment by tuliplab** [comment]
| Flipper | Trainee | Infinity | Alumni
-- | -- | -- | -- | --
DingTalk | Y | Y | Y | Y
Academy Email | N | Y | Y | Y
Seminar Attendance | Y | Y | Y | N
Seminar Presentation | N | Invitation | Y | Invitation
Seminar Q? | N | Y | Y | Y
Reading Team | Y | Y | Invitation | Invitation
Admin Permissin |   |   | Y | Y
ID Hiding |   |   | Y | Y
Blog Subdomain Name |   |   | Y | Y

**Comment by tuliplab** [comment]
@ZiweiHou 

You are allocated with this issue, and please work on it when available.

**Comment by MRen23** [comment]
FLIP Panel  Infinity (Y)  Alumni(Invitation)

**Comment by tuliplab** [comment]
@ZiweiHou 

I have updated the code. Please check it and pay attention to the code formatting.

Now please think how to include the table into the poster.

**Comment by ZiweiHou** [comment]
Done.
